version: '3.8'

services:
  video-maker:
    build: .
    container_name: video-maker
    ports:
      - "80:3001"
    env_file:
      - .env
    volumes:
      - uploads_data:/tmp/vm_uploads
      - renders_data:/tmp/vm_renders
    restart: unless-stopped

volumes:
  uploads_data:
  renders_data:
